// STATUS.md generator — the "garden report". Regenerates a living front page
// for the skill library from what is already on disk: the catalog plus the
// version history. Committed to the playground, GitHub renders it as the
// repo's landing page — a dashboard that is just markdown a graph keeps true.

import { libraryCatalog, listVersions, type GraphVersion, type LibraryEntry } from './graph-store'

export interface SkillStatus extends LibraryEntry {
  versionCount: number
  /** Epoch ms of the newest saved version, if any. */
  lastSaved?: number
}

export interface VersionSave {
  skill: string
  version: GraphVersion
}

export interface StatusReport {
  skills: SkillStatus[]
  /** Saves across all skills, newest first. */
  recentSaves: VersionSave[]
}

/** A delivery line sourced from the playground (issue or commit), passed in by
 *  the caller — collecting them needs the MCP write PAT, which this module
 *  stays free of. */
export interface DeliveryLine {
  title: string
  url: string
  state?: string
  updatedAt?: string
}

export function collectStatus(recentLimit = 10): StatusReport {
  const skills: SkillStatus[] = []
  const saves: VersionSave[] = []

  for (const entry of libraryCatalog()) {
    const versions = listVersions(entry.name)
    skills.push({ ...entry, versionCount: versions.length, lastSaved: versions[0]?.timestamp })
    saves.push(...versions.map(version => ({ skill: entry.name, version })))
  }

  saves.sort((a, b) => b.version.timestamp - a.version.timestamp)
  return { skills, recentSaves: saves.slice(0, recentLimit) }
}

export interface StatusRenderOptions {
  title?: string
  /** Injectable so renders are deterministic in tests. Defaults to now. */
  generatedAt?: Date
  deliveries?: DeliveryLine[]
}

const day = (ts: number) => new Date(ts).toISOString().slice(0, 10)
const minute = (ts: number) => new Date(ts).toISOString().slice(0, 16).replace('T', ' ')

// | breaks table cells; newlines break table rows
const cell = (text: string) => text.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ')

const signature = (ports: Array<{ id: string; optional?: boolean }>) =>
  ports.map(p => `${p.id}${p.optional ? '?' : ''}`).join(', ')

export function renderStatusMarkdown(report: StatusReport, opts: StatusRenderOptions = {}): string {
  const generatedAt = opts.generatedAt ?? new Date()
  const totalVersions = report.skills.reduce((n, s) => n + s.versionCount, 0)
  const totalTests = report.skills.reduce((n, s) => n + s.tested, 0)
  const lastHeartbeat = report.recentSaves[0]?.version.timestamp

  const lines: string[] = []
  lines.push(`# ${opts.title ?? 'Plant — skill library status'}`)
  lines.push('')
  lines.push(
    `**${report.skills.length} skills · ${totalVersions} saved versions · ${totalTests} contract tests** · ` +
    `regenerated ${minute(generatedAt.getTime())} UTC`,
  )
  lines.push('')
  lines.push('Every skill below passed its contract tests at save time — `save_graph` refuses a failing graph, so presence in this table is the evidence.')

  lines.push('', '## Skills', '')
  if (report.skills.length === 0) {
    lines.push('*library is empty*')
  } else {
    lines.push('| Skill | Description | Interface | Tests | Versions | Last saved |')
    lines.push('|---|---|---|---|---|---|')
    for (const s of report.skills) {
      const iface = `(${signature(s.inputs)}) → (${signature(s.outputs)})`
      const saved = s.lastSaved ? day(s.lastSaved) : '—'
      lines.push(`| \`${s.name}\` | ${cell(s.description ?? '—')} | \`${cell(iface)}\` | ${s.tested} | ${s.versionCount} | ${saved} |`)
    }
  }

  lines.push('', '## Recent saves', '')
  if (report.recentSaves.length === 0) {
    lines.push('*no version history on this machine yet — entries appear as `save_graph` runs*')
  } else {
    for (const { skill, version } of report.recentSaves) {
      lines.push(`- ${minute(version.timestamp)} — \`${skill}\` @ \`${version.hash}\``)
    }
    lines.push('', `*Last heartbeat: ${minute(lastHeartbeat!)} UTC*`)
  }

  if (opts.deliveries && opts.deliveries.length > 0) {
    lines.push('', '## Recent deliveries', '')
    for (const d of opts.deliveries) {
      const meta = [d.state, d.updatedAt?.slice(0, 10)].filter(Boolean).join(', ')
      lines.push(`- [${cell(d.title)}](${d.url})${meta ? ` — ${meta}` : ''}`)
    }
  }

  lines.push('', '---', '')
  lines.push('*Generated by status-report from the graph library on disk. Nothing here is hand-maintained.*')
  lines.push('')
  return lines.join('\n')
}
